url: http://thx-lib.org
permalink: pretty
highlighter: pygments
safe: true
exclude: ['CNAME', 'README.md']
lsi: false
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]